/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WordmarkRouteImport } from './routes/wordmark'
import { Route as VoiceRouteImport } from './routes/voice'
import { Route as TypographyRouteImport } from './routes/typography'
import { Route as TypeScaleRouteImport } from './routes/type-scale'
import { Route as TypeRakkasRouteImport } from './routes/type-rakkas'
import { Route as TypeRouteImport } from './routes/type'
import { Route as TokensRouteImport } from './routes/tokens'
import { Route as StrategyRouteImport } from './routes/strategy'
import { Route as StoryRouteImport } from './routes/story'
import { Route as SpacingRouteImport } from './routes/spacing'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as RadiusRouteImport } from './routes/radius'
import { Route as PrayerCardRouteImport } from './routes/prayer-card'
import { Route as PatternsRouteImport } from './routes/patterns'
import { Route as MotionRouteImport } from './routes/motion'
import { Route as MissionRouteImport } from './routes/mission'
import { Route as LogoVariantsRouteImport } from './routes/logo-variants'
import { Route as LogoSystemRouteImport } from './routes/logo-system'
import { Route as LogoMisuseRouteImport } from './routes/logo-misuse'
import { Route as LogoClearspaceRouteImport } from './routes/logo-clearspace'
import { Route as IconsRouteImport } from './routes/icons'
import { Route as IconographyRouteImport } from './routes/iconography'
import { Route as FoundationsRouteImport } from './routes/foundations'
import { Route as FormsRouteImport } from './routes/forms'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as DosDontsRouteImport } from './routes/dos-donts'
import { Route as CreditsRouteImport } from './routes/credits'
import { Route as ContentsRouteImport } from './routes/contents'
import { Route as ComponentsRouteImport } from './routes/components'
import { Route as ColorSystemRouteImport } from './routes/color-system'
import { Route as ColorRoyalRouteImport } from './routes/color-royal'
import { Route as ColorRatiosRouteImport } from './routes/color-ratios'
import { Route as ColorRouteImport } from './routes/color'
import { Route as CardsRouteImport } from './routes/cards'
import { Route as ButtonsRouteImport } from './routes/buttons'
import { Route as BraceRouteImport } from './routes/brace'
import { Route as ApplicationsRouteImport } from './routes/applications'
import { Route as IndexRouteImport } from './routes/index'

const WordmarkRoute = WordmarkRouteImport.update({
  id: '/wordmark',
  path: '/wordmark',
  getParentRoute: () => rootRouteImport,
} as any)
const VoiceRoute = VoiceRouteImport.update({
  id: '/voice',
  path: '/voice',
  getParentRoute: () => rootRouteImport,
} as any)
const TypographyRoute = TypographyRouteImport.update({
  id: '/typography',
  path: '/typography',
  getParentRoute: () => rootRouteImport,
} as any)
const TypeScaleRoute = TypeScaleRouteImport.update({
  id: '/type-scale',
  path: '/type-scale',
  getParentRoute: () => rootRouteImport,
} as any)
const TypeRakkasRoute = TypeRakkasRouteImport.update({
  id: '/type-rakkas',
  path: '/type-rakkas',
  getParentRoute: () => rootRouteImport,
} as any)
const TypeRoute = TypeRouteImport.update({
  id: '/type',
  path: '/type',
  getParentRoute: () => rootRouteImport,
} as any)
const TokensRoute = TokensRouteImport.update({
  id: '/tokens',
  path: '/tokens',
  getParentRoute: () => rootRouteImport,
} as any)
const StrategyRoute = StrategyRouteImport.update({
  id: '/strategy',
  path: '/strategy',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryRoute = StoryRouteImport.update({
  id: '/story',
  path: '/story',
  getParentRoute: () => rootRouteImport,
} as any)
const SpacingRoute = SpacingRouteImport.update({
  id: '/spacing',
  path: '/spacing',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const RadiusRoute = RadiusRouteImport.update({
  id: '/radius',
  path: '/radius',
  getParentRoute: () => rootRouteImport,
} as any)
const PrayerCardRoute = PrayerCardRouteImport.update({
  id: '/prayer-card',
  path: '/prayer-card',
  getParentRoute: () => rootRouteImport,
} as any)
const PatternsRoute = PatternsRouteImport.update({
  id: '/patterns',
  path: '/patterns',
  getParentRoute: () => rootRouteImport,
} as any)
const MotionRoute = MotionRouteImport.update({
  id: '/motion',
  path: '/motion',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionRoute = MissionRouteImport.update({
  id: '/mission',
  path: '/mission',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoVariantsRoute = LogoVariantsRouteImport.update({
  id: '/logo-variants',
  path: '/logo-variants',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoSystemRoute = LogoSystemRouteImport.update({
  id: '/logo-system',
  path: '/logo-system',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoMisuseRoute = LogoMisuseRouteImport.update({
  id: '/logo-misuse',
  path: '/logo-misuse',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoClearspaceRoute = LogoClearspaceRouteImport.update({
  id: '/logo-clearspace',
  path: '/logo-clearspace',
  getParentRoute: () => rootRouteImport,
} as any)
const IconsRoute = IconsRouteImport.update({
  id: '/icons',
  path: '/icons',
  getParentRoute: () => rootRouteImport,
} as any)
const IconographyRoute = IconographyRouteImport.update({
  id: '/iconography',
  path: '/iconography',
  getParentRoute: () => rootRouteImport,
} as any)
const FoundationsRoute = FoundationsRouteImport.update({
  id: '/foundations',
  path: '/foundations',
  getParentRoute: () => rootRouteImport,
} as any)
const FormsRoute = FormsRouteImport.update({
  id: '/forms',
  path: '/forms',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const DosDontsRoute = DosDontsRouteImport.update({
  id: '/dos-donts',
  path: '/dos-donts',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditsRoute = CreditsRouteImport.update({
  id: '/credits',
  path: '/credits',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentsRoute = ContentsRouteImport.update({
  id: '/contents',
  path: '/contents',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsRoute = ComponentsRouteImport.update({
  id: '/components',
  path: '/components',
  getParentRoute: () => rootRouteImport,
} as any)
const ColorSystemRoute = ColorSystemRouteImport.update({
  id: '/color-system',
  path: '/color-system',
  getParentRoute: () => rootRouteImport,
} as any)
const ColorRoyalRoute = ColorRoyalRouteImport.update({
  id: '/color-royal',
  path: '/color-royal',
  getParentRoute: () => rootRouteImport,
} as any)
const ColorRatiosRoute = ColorRatiosRouteImport.update({
  id: '/color-ratios',
  path: '/color-ratios',
  getParentRoute: () => rootRouteImport,
} as any)
const ColorRoute = ColorRouteImport.update({
  id: '/color',
  path: '/color',
  getParentRoute: () => rootRouteImport,
} as any)
const CardsRoute = CardsRouteImport.update({
  id: '/cards',
  path: '/cards',
  getParentRoute: () => rootRouteImport,
} as any)
const ButtonsRoute = ButtonsRouteImport.update({
  id: '/buttons',
  path: '/buttons',
  getParentRoute: () => rootRouteImport,
} as any)
const BraceRoute = BraceRouteImport.update({
  id: '/brace',
  path: '/brace',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsRoute = ApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRoute
  '/brace': typeof BraceRoute
  '/buttons': typeof ButtonsRoute
  '/cards': typeof CardsRoute
  '/color': typeof ColorRoute
  '/color-ratios': typeof ColorRatiosRoute
  '/color-royal': typeof ColorRoyalRoute
  '/color-system': typeof ColorSystemRoute
  '/components': typeof ComponentsRoute
  '/contents': typeof ContentsRoute
  '/credits': typeof CreditsRoute
  '/dos-donts': typeof DosDontsRoute
  '/feedback': typeof FeedbackRoute
  '/forms': typeof FormsRoute
  '/foundations': typeof FoundationsRoute
  '/iconography': typeof IconographyRoute
  '/icons': typeof IconsRoute
  '/logo-clearspace': typeof LogoClearspaceRoute
  '/logo-misuse': typeof LogoMisuseRoute
  '/logo-system': typeof LogoSystemRoute
  '/logo-variants': typeof LogoVariantsRoute
  '/mission': typeof MissionRoute
  '/motion': typeof MotionRoute
  '/patterns': typeof PatternsRoute
  '/prayer-card': typeof PrayerCardRoute
  '/radius': typeof RadiusRoute
  '/resources': typeof ResourcesRoute
  '/spacing': typeof SpacingRoute
  '/story': typeof StoryRoute
  '/strategy': typeof StrategyRoute
  '/tokens': typeof TokensRoute
  '/type': typeof TypeRoute
  '/type-rakkas': typeof TypeRakkasRoute
  '/type-scale': typeof TypeScaleRoute
  '/typography': typeof TypographyRoute
  '/voice': typeof VoiceRoute
  '/wordmark': typeof WordmarkRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRoute
  '/brace': typeof BraceRoute
  '/buttons': typeof ButtonsRoute
  '/cards': typeof CardsRoute
  '/color': typeof ColorRoute
  '/color-ratios': typeof ColorRatiosRoute
  '/color-royal': typeof ColorRoyalRoute
  '/color-system': typeof ColorSystemRoute
  '/components': typeof ComponentsRoute
  '/contents': typeof ContentsRoute
  '/credits': typeof CreditsRoute
  '/dos-donts': typeof DosDontsRoute
  '/feedback': typeof FeedbackRoute
  '/forms': typeof FormsRoute
  '/foundations': typeof FoundationsRoute
  '/iconography': typeof IconographyRoute
  '/icons': typeof IconsRoute
  '/logo-clearspace': typeof LogoClearspaceRoute
  '/logo-misuse': typeof LogoMisuseRoute
  '/logo-system': typeof LogoSystemRoute
  '/logo-variants': typeof LogoVariantsRoute
  '/mission': typeof MissionRoute
  '/motion': typeof MotionRoute
  '/patterns': typeof PatternsRoute
  '/prayer-card': typeof PrayerCardRoute
  '/radius': typeof RadiusRoute
  '/resources': typeof ResourcesRoute
  '/spacing': typeof SpacingRoute
  '/story': typeof StoryRoute
  '/strategy': typeof StrategyRoute
  '/tokens': typeof TokensRoute
  '/type': typeof TypeRoute
  '/type-rakkas': typeof TypeRakkasRoute
  '/type-scale': typeof TypeScaleRoute
  '/typography': typeof TypographyRoute
  '/voice': typeof VoiceRoute
  '/wordmark': typeof WordmarkRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRoute
  '/brace': typeof BraceRoute
  '/buttons': typeof ButtonsRoute
  '/cards': typeof CardsRoute
  '/color': typeof ColorRoute
  '/color-ratios': typeof ColorRatiosRoute
  '/color-royal': typeof ColorRoyalRoute
  '/color-system': typeof ColorSystemRoute
  '/components': typeof ComponentsRoute
  '/contents': typeof ContentsRoute
  '/credits': typeof CreditsRoute
  '/dos-donts': typeof DosDontsRoute
  '/feedback': typeof FeedbackRoute
  '/forms': typeof FormsRoute
  '/foundations': typeof FoundationsRoute
  '/iconography': typeof IconographyRoute
  '/icons': typeof IconsRoute
  '/logo-clearspace': typeof LogoClearspaceRoute
  '/logo-misuse': typeof LogoMisuseRoute
  '/logo-system': typeof LogoSystemRoute
  '/logo-variants': typeof LogoVariantsRoute
  '/mission': typeof MissionRoute
  '/motion': typeof MotionRoute
  '/patterns': typeof PatternsRoute
  '/prayer-card': typeof PrayerCardRoute
  '/radius': typeof RadiusRoute
  '/resources': typeof ResourcesRoute
  '/spacing': typeof SpacingRoute
  '/story': typeof StoryRoute
  '/strategy': typeof StrategyRoute
  '/tokens': typeof TokensRoute
  '/type': typeof TypeRoute
  '/type-rakkas': typeof TypeRakkasRoute
  '/type-scale': typeof TypeScaleRoute
  '/typography': typeof TypographyRoute
  '/voice': typeof VoiceRoute
  '/wordmark': typeof WordmarkRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/applications'
    | '/brace'
    | '/buttons'
    | '/cards'
    | '/color'
    | '/color-ratios'
    | '/color-royal'
    | '/color-system'
    | '/components'
    | '/contents'
    | '/credits'
    | '/dos-donts'
    | '/feedback'
    | '/forms'
    | '/foundations'
    | '/iconography'
    | '/icons'
    | '/logo-clearspace'
    | '/logo-misuse'
    | '/logo-system'
    | '/logo-variants'
    | '/mission'
    | '/motion'
    | '/patterns'
    | '/prayer-card'
    | '/radius'
    | '/resources'
    | '/spacing'
    | '/story'
    | '/strategy'
    | '/tokens'
    | '/type'
    | '/type-rakkas'
    | '/type-scale'
    | '/typography'
    | '/voice'
    | '/wordmark'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/applications'
    | '/brace'
    | '/buttons'
    | '/cards'
    | '/color'
    | '/color-ratios'
    | '/color-royal'
    | '/color-system'
    | '/components'
    | '/contents'
    | '/credits'
    | '/dos-donts'
    | '/feedback'
    | '/forms'
    | '/foundations'
    | '/iconography'
    | '/icons'
    | '/logo-clearspace'
    | '/logo-misuse'
    | '/logo-system'
    | '/logo-variants'
    | '/mission'
    | '/motion'
    | '/patterns'
    | '/prayer-card'
    | '/radius'
    | '/resources'
    | '/spacing'
    | '/story'
    | '/strategy'
    | '/tokens'
    | '/type'
    | '/type-rakkas'
    | '/type-scale'
    | '/typography'
    | '/voice'
    | '/wordmark'
  id:
    | '__root__'
    | '/'
    | '/applications'
    | '/brace'
    | '/buttons'
    | '/cards'
    | '/color'
    | '/color-ratios'
    | '/color-royal'
    | '/color-system'
    | '/components'
    | '/contents'
    | '/credits'
    | '/dos-donts'
    | '/feedback'
    | '/forms'
    | '/foundations'
    | '/iconography'
    | '/icons'
    | '/logo-clearspace'
    | '/logo-misuse'
    | '/logo-system'
    | '/logo-variants'
    | '/mission'
    | '/motion'
    | '/patterns'
    | '/prayer-card'
    | '/radius'
    | '/resources'
    | '/spacing'
    | '/story'
    | '/strategy'
    | '/tokens'
    | '/type'
    | '/type-rakkas'
    | '/type-scale'
    | '/typography'
    | '/voice'
    | '/wordmark'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApplicationsRoute: typeof ApplicationsRoute
  BraceRoute: typeof BraceRoute
  ButtonsRoute: typeof ButtonsRoute
  CardsRoute: typeof CardsRoute
  ColorRoute: typeof ColorRoute
  ColorRatiosRoute: typeof ColorRatiosRoute
  ColorRoyalRoute: typeof ColorRoyalRoute
  ColorSystemRoute: typeof ColorSystemRoute
  ComponentsRoute: typeof ComponentsRoute
  ContentsRoute: typeof ContentsRoute
  CreditsRoute: typeof CreditsRoute
  DosDontsRoute: typeof DosDontsRoute
  FeedbackRoute: typeof FeedbackRoute
  FormsRoute: typeof FormsRoute
  FoundationsRoute: typeof FoundationsRoute
  IconographyRoute: typeof IconographyRoute
  IconsRoute: typeof IconsRoute
  LogoClearspaceRoute: typeof LogoClearspaceRoute
  LogoMisuseRoute: typeof LogoMisuseRoute
  LogoSystemRoute: typeof LogoSystemRoute
  LogoVariantsRoute: typeof LogoVariantsRoute
  MissionRoute: typeof MissionRoute
  MotionRoute: typeof MotionRoute
  PatternsRoute: typeof PatternsRoute
  PrayerCardRoute: typeof PrayerCardRoute
  RadiusRoute: typeof RadiusRoute
  ResourcesRoute: typeof ResourcesRoute
  SpacingRoute: typeof SpacingRoute
  StoryRoute: typeof StoryRoute
  StrategyRoute: typeof StrategyRoute
  TokensRoute: typeof TokensRoute
  TypeRoute: typeof TypeRoute
  TypeRakkasRoute: typeof TypeRakkasRoute
  TypeScaleRoute: typeof TypeScaleRoute
  TypographyRoute: typeof TypographyRoute
  VoiceRoute: typeof VoiceRoute
  WordmarkRoute: typeof WordmarkRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wordmark': {
      id: '/wordmark'
      path: '/wordmark'
      fullPath: '/wordmark'
      preLoaderRoute: typeof WordmarkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voice': {
      id: '/voice'
      path: '/voice'
      fullPath: '/voice'
      preLoaderRoute: typeof VoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/typography': {
      id: '/typography'
      path: '/typography'
      fullPath: '/typography'
      preLoaderRoute: typeof TypographyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/type-scale': {
      id: '/type-scale'
      path: '/type-scale'
      fullPath: '/type-scale'
      preLoaderRoute: typeof TypeScaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/type-rakkas': {
      id: '/type-rakkas'
      path: '/type-rakkas'
      fullPath: '/type-rakkas'
      preLoaderRoute: typeof TypeRakkasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/type': {
      id: '/type'
      path: '/type'
      fullPath: '/type'
      preLoaderRoute: typeof TypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tokens': {
      id: '/tokens'
      path: '/tokens'
      fullPath: '/tokens'
      preLoaderRoute: typeof TokensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strategy': {
      id: '/strategy'
      path: '/strategy'
      fullPath: '/strategy'
      preLoaderRoute: typeof StrategyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story': {
      id: '/story'
      path: '/story'
      fullPath: '/story'
      preLoaderRoute: typeof StoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spacing': {
      id: '/spacing'
      path: '/spacing'
      fullPath: '/spacing'
      preLoaderRoute: typeof SpacingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/radius': {
      id: '/radius'
      path: '/radius'
      fullPath: '/radius'
      preLoaderRoute: typeof RadiusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prayer-card': {
      id: '/prayer-card'
      path: '/prayer-card'
      fullPath: '/prayer-card'
      preLoaderRoute: typeof PrayerCardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patterns': {
      id: '/patterns'
      path: '/patterns'
      fullPath: '/patterns'
      preLoaderRoute: typeof PatternsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/motion': {
      id: '/motion'
      path: '/motion'
      fullPath: '/motion'
      preLoaderRoute: typeof MotionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mission': {
      id: '/mission'
      path: '/mission'
      fullPath: '/mission'
      preLoaderRoute: typeof MissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logo-variants': {
      id: '/logo-variants'
      path: '/logo-variants'
      fullPath: '/logo-variants'
      preLoaderRoute: typeof LogoVariantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logo-system': {
      id: '/logo-system'
      path: '/logo-system'
      fullPath: '/logo-system'
      preLoaderRoute: typeof LogoSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logo-misuse': {
      id: '/logo-misuse'
      path: '/logo-misuse'
      fullPath: '/logo-misuse'
      preLoaderRoute: typeof LogoMisuseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logo-clearspace': {
      id: '/logo-clearspace'
      path: '/logo-clearspace'
      fullPath: '/logo-clearspace'
      preLoaderRoute: typeof LogoClearspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/icons': {
      id: '/icons'
      path: '/icons'
      fullPath: '/icons'
      preLoaderRoute: typeof IconsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iconography': {
      id: '/iconography'
      path: '/iconography'
      fullPath: '/iconography'
      preLoaderRoute: typeof IconographyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foundations': {
      id: '/foundations'
      path: '/foundations'
      fullPath: '/foundations'
      preLoaderRoute: typeof FoundationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forms': {
      id: '/forms'
      path: '/forms'
      fullPath: '/forms'
      preLoaderRoute: typeof FormsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dos-donts': {
      id: '/dos-donts'
      path: '/dos-donts'
      fullPath: '/dos-donts'
      preLoaderRoute: typeof DosDontsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credits': {
      id: '/credits'
      path: '/credits'
      fullPath: '/credits'
      preLoaderRoute: typeof CreditsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contents': {
      id: '/contents'
      path: '/contents'
      fullPath: '/contents'
      preLoaderRoute: typeof ContentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components': {
      id: '/components'
      path: '/components'
      fullPath: '/components'
      preLoaderRoute: typeof ComponentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/color-system': {
      id: '/color-system'
      path: '/color-system'
      fullPath: '/color-system'
      preLoaderRoute: typeof ColorSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/color-royal': {
      id: '/color-royal'
      path: '/color-royal'
      fullPath: '/color-royal'
      preLoaderRoute: typeof ColorRoyalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/color-ratios': {
      id: '/color-ratios'
      path: '/color-ratios'
      fullPath: '/color-ratios'
      preLoaderRoute: typeof ColorRatiosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/color': {
      id: '/color'
      path: '/color'
      fullPath: '/color'
      preLoaderRoute: typeof ColorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cards': {
      id: '/cards'
      path: '/cards'
      fullPath: '/cards'
      preLoaderRoute: typeof CardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buttons': {
      id: '/buttons'
      path: '/buttons'
      fullPath: '/buttons'
      preLoaderRoute: typeof ButtonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brace': {
      id: '/brace'
      path: '/brace'
      fullPath: '/brace'
      preLoaderRoute: typeof BraceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications': {
      id: '/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof ApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApplicationsRoute: ApplicationsRoute,
  BraceRoute: BraceRoute,
  ButtonsRoute: ButtonsRoute,
  CardsRoute: CardsRoute,
  ColorRoute: ColorRoute,
  ColorRatiosRoute: ColorRatiosRoute,
  ColorRoyalRoute: ColorRoyalRoute,
  ColorSystemRoute: ColorSystemRoute,
  ComponentsRoute: ComponentsRoute,
  ContentsRoute: ContentsRoute,
  CreditsRoute: CreditsRoute,
  DosDontsRoute: DosDontsRoute,
  FeedbackRoute: FeedbackRoute,
  FormsRoute: FormsRoute,
  FoundationsRoute: FoundationsRoute,
  IconographyRoute: IconographyRoute,
  IconsRoute: IconsRoute,
  LogoClearspaceRoute: LogoClearspaceRoute,
  LogoMisuseRoute: LogoMisuseRoute,
  LogoSystemRoute: LogoSystemRoute,
  LogoVariantsRoute: LogoVariantsRoute,
  MissionRoute: MissionRoute,
  MotionRoute: MotionRoute,
  PatternsRoute: PatternsRoute,
  PrayerCardRoute: PrayerCardRoute,
  RadiusRoute: RadiusRoute,
  ResourcesRoute: ResourcesRoute,
  SpacingRoute: SpacingRoute,
  StoryRoute: StoryRoute,
  StrategyRoute: StrategyRoute,
  TokensRoute: TokensRoute,
  TypeRoute: TypeRoute,
  TypeRakkasRoute: TypeRakkasRoute,
  TypeScaleRoute: TypeScaleRoute,
  TypographyRoute: TypographyRoute,
  VoiceRoute: VoiceRoute,
  WordmarkRoute: WordmarkRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
